language: c

os:
    - linux

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required

compiler:
    - gcc


env:
    global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
        - secure: "mxfCT3lOPehSnjbvK9JtzGq32dIgGbDRh0bWYi3VNd0JXfSEiyPfbYv7Zm3MUa5XmzhQmOJRw2VphaL6m4J/t41VdxbzuhjdohT/O/D1L3aJNU/DCrcul1LUYU7Frfk8JQ5tnHaZuI5+rdyZIAOd2K35kWxhh0gzqTXXt07jNUKZuktN1k4mnnJ8uJLNAQQE69zuJPNyKjnhCx/bD4/KZwU9QGk3eX8DxRo9UCe1cm5M5qGrku/QcCE4CVgaKSYcSEiumsjraFVlD+D2+OzH3l+l6pXoAXHoXYkz0Iko291IDxNDDbq/vpxAgieVtgQdIv/eBwMjnfSMC2xUS/zQvu1DsC3yoaDq2EeZdBs5HsaQiOHMCB9Pdlrloykb8RQqYvAjvrfKwy0BcOW1Z+6cOe7A1hiZptarPk3nki9vuTeUMo8/TkJXKQkDlutocaBjt1je3l4lGiQkKPsfCla/XF1AuYaPvo37hqHNE8lCNteIklGNHT4T4gQnHgq2ZqxLW2aaewJMTDOxFuAFQskkHxwDUFoQGAvPNUbBEJvD0MOMGFJxwiUZQMDjarvasD4PAw5cgWMABXPjgy35Ycfx+cGPWnx6xQhXT8OpVl8wIUCwUSQ8K5l+yccMwe38J2H9tjq6ahLe7MM/ZK8H4I720mZLpNTdbwrXm6aG0ERsYpg="

addons:
  coverity_scan:
    project:
      name: "schmidtw/parodus2fs"
      description: "A simple adapter that lets you access files via Xmidt."
    notification_email: weston_schmidt@alumni.purdue.edu
    build_command_prepend: "mkdir coverity_build && cd coverity_build && cmake .."
    build_command:   "make"
    branch_pattern: disable_master
    
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install cunit valgrind; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov valgrind; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi


install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq check libcunit1 libcunit1-dev uuid-dev valgrind

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov; fi
